### ISSUE TITLE
Проверка 1

### ISSUE THREAD

**Issue by KseeBMSTU** [matveybaykalov/Homework_2_Sem2#1]
- [x] 1. MapIteraror == -- потерян const& в параметре
- [x] 2. Ошибки в реализации и использовании reverse iterator'ов. См. иллюстрацию [в документации](https://en.cppreference.com/w/cpp/container/map/rend)
- [x] 3. insert делает несколько проходов. Давайте проще
- [x] 4. count, find, at - зачем проходить всё хранилище, если значения упорядочены по ключу?
- [x] 5. node.operator->() - очень дикий код. Оператор -> перегружается, чтобы была возможность обращаться к полям элемента. Если вы хотите получить адрес, получайте его оператором получения адреса (через элемент). В коде должны быть понятны ваши намерения)
- [x] 6. erase -- почему i <= _size? Почему <=? На последней итерации доступ к элементам  с индексами size и size + 1 ;)
- [x] 7. merge -- большая сложность. Давайте оптимизировать
- [x] 8. extract по итератору. Вы знаете местоположение элемента (сложность доступа О(1)) и можете начать сдвигать элементы, но решаете поискать его по ключу (линейная сложность).
- [x] 9. [] у map используется для доступа по ключу, а не для индексации

У вас много функций использует поиск элемента. Я думаю, вы способны значительно улучшить реализацию, сведя сложность методов к логарифмической (как в документации). Почитайте про бинарный поиск :)

Сразу предупрежу, что это может быть не исчерпывающий список замечаний, на следующей итерации могу ещё что-то найти. Но чтобы вы не ждали, пока я смогу всё это хорошенько прогнать, правьте пока это.

**Comment by matveybaykalov** [comment]
Надеюсь все ошибки исправил, единственное хотел бы оставить комментарии по некоторым пунктам
1. Исправил
2. Теперь revers iterator'ы работают правильно и rend возвращает элемент идущий перед первым.
3. Немного переделал insert, сейчас у него сложность n+log2(n)
4. Переработал эти функции теперь их сложность log2(n)
5. Исправил, теперь получение адреса происходит через доступ к полю
6. Согласен, что в предыдущей реализации <= работало некорректно, но сейчас <=  нужно оставить, потому что на нулевой позиции находится элемент, необходимый для работы revers iterator'ов.
7. Исправил, теперь сложность n1 + n2, где n1 и n2 размеры двух контейнеров.
8. Исправил 
9. Исправил
